version: "3.8"
services:
  frontend:
    platform: linux/amd64
    image: apokryphos97/promtior-frontend:latest
    ports:
      - "80:80"
  backend:
    platform: linux/amd64
    image: apokryphos97/promtior-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    depends_on:
      - frontend

volumes:
  huggingface_cache: